import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Land Sathi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-gray-100 text-gray-900"}>
        <header style={{ backgroundColor: "pink", padding: "10px" }}>
          <p>Header it is baby!</p>
        </header>
        {children}  
        <footer style={{ backgroundColor: "beige", padding: "10px" }}>
          <p>Footer it is baby!</p>
        </footer>
      </body>
    </html>
  );
}
